<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simpleroute"
 *
 * Auto generated by Extension Builder 2015-02-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Simple Maps Directions',
	'description' => 'Simple Plugin for point-to-point directions. For now, Google Maps only.',
	'category' => 'plugin',
	'author' => 'Cedric Ziel',
	'author_email' => 'cedric@cedric-ziel.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
